---
abstract: 'Different kinds of subtests.'
author:
  - 'Bert Vanderbauwhede <batlock666@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Subtests
provides:
  Test::Subtests:
    file: lib/Test/Subtests.pm
    version: 0.01
requires:
  Test::Builder: 0
  Test::Builder::Module: 0
resources:
  license: http://www.gnu.org/licenses/lgpl-3.0.txt
version: 0.01
